### ISSUE TITLE
L5 not supported

### ISSUE THREAD

**Issue by MartijnThomas** [GrahamCampbell/Laravel-Database#4]
Graham, on your website you state that this package has L5 support, but when I try to pull it in it 'crashes' on the 4.2 packages :)

**Comment by GrahamCampbell** [comment]
Sorry, my website is quite badly outdated again. I won't be maintaining a Laravel 5 version of this package. I've actually moved this stuff directly into my credentials package as part of Bootstrap CMS.
https://github.com/BootstrapCMS/Credentials/tree/master/src/Models
https://github.com/BootstrapCMS/Credentials/tree/master/src/Repositories
